### ISSUE TITLE
Make player name a grouping on the table so it always shows up on mobile 

### ISSUE THREAD

**Issue by bradykey** [bradykey/softball-reference-ui#13]
This is essentially what th fantasy baseball app does and is another way to FREEZE the name columb

**Comment by bradykey** [comment]
Or do a sticky css col:

https://github.com/vuetifyjs/vuetify/issues/4652#issuecomment-622994998

**Comment by bradykey** [comment]
```css
<style>
.sticky1 table > tbody > tr > td:nth-child(1),
table > thead > tr > th:nth-child(1) {
  position: sticky !important;
  position: -webkit-sticky !important;
  left: 0;
  z-index: 9998;
  background: #1e1e1e;
}
.sticky1 table > thead > tr > th:nth-child(1) {
  z-index: 9999 !important;
}

.sticky2 table > tbody > tr > td:nth-child(1),
table > thead > tr > th:nth-child(1) {
  position: sticky !important;
  position: -webkit-sticky !important;
  left: 0;
  z-index: 9998;
  background: #1e1e1e;
}
.sticky2 table > thead > tr > th:nth-child(1) {
  z-index: 9999 !important;
}
.sticky2 table > tbody > tr > td:nth-child(2),
table > thead > tr > th:nth-child(2) {
  position: sticky !important;
  position: -webkit-sticky !important;
  left: 0;
  z-index: 9998;
  background: #1e1e1e;
}
.sticky2 table > thead > tr > th:nth-child(2) {
  z-index: 9999 !important;
}
</style>

```
